// in Typescript, union to data types enables the data to be defined to one or two or multiple different data types of any except that it will give the error at compilation as compiler error:

let bishalData : (number|string|boolean)[] = [1, 2,3, "Bishal", "suzan", true];
// let bishalDataCopy : (number|string)[] = [1, 2,3, "Bishal", "suzan", true, 1.3];

// console.log(bishalDataCopy); // this will give the compile error boolen value cannot be assaigned as there is not the boolen data type defined.
console.log(bishalData); 
console.log(typeof(bishalData)); // this gives the data type as an object
console.log(typeof(bishalData[2])); // this auto identifies the data type as a number as there is numeric value at that index.
console.log(typeof(bishalData[3])); // this auto identifies the data type as a string as there is string value at that index.



function displayType(geeks: (string | number)) { 
    if(typeof(geeks) === "number") 
        console.log('geeks is number.') 
    else if(typeof(geeks) === "string") 
        console.log('geeks is string.') 
} 
  
// Output: Code is number.  
displayType(49);  
  
// Output: Code is string. 
displayType("GFG");  
  
// // Compiler Error: Argument of type 'true' is not  
// // assignable to a parameter of type string | number 
// displayType(true);




//Generated by typescript 1.8.10 
var arr = [2, 5, 7, 5, 11, 15]; 
  
console.log("Display the array elements"); 
  
// Loop to display array elements 
for (var i = 0; i < arr.length; i++) { 
   console.log(arr[i]); 
} 
  
// Declare another array 
var arr1 = ["Geeks", "G4G", "GFG", "GeeksforGeeks"]; 
  
console.log("Display the array elements"); 
  
// Loop to display the array elements 
for (var i = 0; i < arr1.length; i++) { 
   console.log(arr1[i]); 
} 

console.log(arr); // this does print the whole array and above type is used to print the array element